[package]
name = "hcml"
version = "0.1.0"
edition = "2021"

[dependencies]
either = "1.13.0"
getset = "0.1.4"
itertools = "0.14.0"
pest = "2.7.15"
pest_derive = "2.7.15"
smart-default = "0.7.1"
thiserror = "2.0.11"
