name: CI

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Reduce permissions to minimum
permissions:
  # To fetch code
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "ci"
  cancel-in-progress: false

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build and test project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1.2.1
        with:
          bins: cargo-nextest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tests
        run: cargo nextest run --verbose

  clippy:
    name: Clippy lints
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1.2.1
        with:
          components: clippy
      - name: Clippy
        run: cargo clippy

  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1.2.1
        with:
          bins: cargo-msrv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify msrv
        run: cargo msrv verify
